
# Definition of QA pipeline at SonarSource

TEST:
  - plugin
  - ruling

SQ_VERSION:
  - DEV
  - LATEST_RELEASE[6.7]
  - LATEST_RELEASE

exclude:
  - TEST: ruling
    SQ_VERSION: DEV
  - TEST: ruling
    SQ_VERSION: LATEST_RELEASE[6.7]

